defaults:
  - suite: gym
  - agent: fish # Optimizer will be initialized inside the agent

object: cube_flipping # plier_picking #bowl_picking
# data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/${object}
data_path: /scratch/yd2032/Desktop/holobot_data/${object}

image_out_dir: /scratch/yd2032/Desktop/fish_implementation/2023.06.14/15-23_temporal_ssl_bs_32_epochs_500_lr_1e-05_cube_flipping
image_model_type: temporal
tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/12-32_tactile_byol_bs_512_tactile_play_data_alexnet_pretrained_duration_120 # - Play data encoder
tactile_model_type: byol # It could be ssl/byol as well

reward_representations: ['image']
policy_representations: ['image','features']

seed: 42 
# device: cuda
device: cpu

num_train_frames: 10000 # Total training numbers
num_seed_frames: 150 # Have the first episode random
eval_every_frames: 600 # Evaluate in each every 600 frames
num_eval_episodes: 20
evaluate: False

buffer_path: null

# FISH and environment params
expert_id: 0 # 24
# expert_demo_nums: [15] # Plier Picking, need to change this
expert_demo_nums: [25]

reward_matching_steps: 1 # We will only match the last 20 steps through the demonstration
match_from_both: True # If true we'll match the rewards from both of the 
episode_frame_matches: 10 
expert_frame_matches: 1
exponential_weight_init: False # If true the initial weight in the ot reward will be exponential - currently it's equal importance to all timeframes
end_frames_repeat: 1 # Stack the last frames for 20 times
sum_experts: False
scale_representations: False
exponential_exploration: False # This is to explore sometimes when it's stuck
exponential_offset_exploration: False # TODO: Test this - offset added is lowered exponentially
exploration: ou_noise
base_policy: openloop
rewards: sinkhorn_cosine # it was sinkhorn cosine
ssim_base_factor: 0.7 # It's assumed to give higher rewards
mock_env: False # If set to true we will be using mock demos as the environment interaction
mock_demo_nums: [10, 12, 13, 15, 2, 7] # Use all of them # [13,15,2,7] # 15 is the expert demo in the agent
camera_num: 0

# Agent params 
bc_regularize: False
features_repeat: 5 # Number to how many times to repeat the features as the input to the model

# Replay buffer params
replay_buffer_size: 150000
replay_buffer_num_workers: 2
nstep: 3
batch_size: 256

# Recorder
save_eval_video: True 
save_train_video: True 
# NOTE: visualize the training matrix 
save_train_cost_matrices: False

# Snapshot loading
load_snapshot: False
snapshot_weight: /home/irmak/Workspace/tactile-learning/weights/corl_trainings/plier_picking/snapshot_plier_picking_gen_0_1.pt

log: False
experiment: ${now:%Y.%m.%d}T${now:%H-%M}_${object}_test_1

# hydra configuration - should be received separately
hydra:
    run:
        dir: /scratch/yd2032/Desktop/fish_implementation/FISH/out/${now:%Y.%m.%d}/${now:%H-%M}_${experiment}
