_target_: deployer.vinn.VINN
data_path: /scratch/yd2032/Desktop/holobot_data

# Directories to change by the user depending on where they saved the data
deployment_dump_dir: /scratch/yd2032/Desktop/byol_implementation/deploy
# tactile_out_dir: /tactile/model/out/dir
image_out_dir: /scratch/yd2032/Desktop/byol_implementation/2023.06.01/18-47_image_byol_bs_32_epochs_500_lr_1e-05_cube_flipping
nn_buffer_size: 20
nn_k: 20
representation_types: ['image'] # Observations used in the representations
representation_importance: [1] # We will multiply the distances with these given numbers when using in scaled nearest neighbors
demos_to_use: [] # Leave empty to use all the demos in the evaluation
view_num: 0
open_loop: false
representation_path: /scratch/yd2032/Desktop/byol_implementation/representation/2023.06.12/16-42_representation
dump_path: /scratch/yd2032/Desktop/byol_implementation